### ISSUE TITLE
Instantly runs out of memory -- memory leak

### ISSUE THREAD

**Issue by Algomorph** [valette/Wavemesh#2]
Hi, thanks for putting this code up!
I've managed to compile it, but I'm instantly running out of memory. I'm loading a ~0.2 mb .off file, exported out of meshlab, with the -c flag and the -d 1 argument [EDIT: fails regardless of the -d argument]. I'm running Ubuntu 16.04. I've custom-compiled VTK 5.2 for this. The machine has 32 GB of RAM, so there must be some kind of memory leak. Any suggestions?

**Comment by valette** [comment]
I do not remember about the -c flag, and there does not seem to be such option...

**Comment by Algomorph** [comment]
@valette , sorry, just the "c" option without the hyphen, for compression.

**Comment by valette** [comment]
Do you have a log output? If there is no output, I suspect there is an issue with the file format. Could you try an other format such as .obj or .ply ?

**Comment by Algomorph** [comment]
The original file was converted from .ply to .off in MeshLab 1.3.2. I tried other files with other formats and other converters, seems like this specific problem is only with the .off files. However, I'm more often than not getting segfaults on .obj and .ply files, like in #3. I'm currently exploring the geometry in search for unwanted artifacts.
P.S. for the out-of-memory case, there is no log output.
