### ISSUE TITLE
filters declaration 

### ISSUE THREAD

**Issue by Salwathouir** [valette/Wavemesh#5]
Hello sir,
could you tell me where  both filters of analysis and synthesis were declared in your code, please

**Comment by valette** [comment]
as written in wavemesh.cxx:
https://github.com/valette/Wavemesh/blob/master/Compression/wavemesh.cxx

the multiresolution filter is in vtkMultiresolutionIO.h :
https://github.com/valette/Wavemesh/blob/master/Compression/vtkMultiresolutionIO.h

It uses a cascade of vtkWaveletSubdivisionFilter, defined here:
https://github.com/valette/Wavemesh/blob/master/Compression/vtkWaveletSubdivisionFilter.h

each vtkWaveletSubdivisionFilter is both an analysis and synthesis filter
