### ISSUE TITLE
I need some clarifications please

### ISSUE THREAD

**Issue by Salwathouir** [valette/Wavemesh#6]
hello Sir,
I am new with progressive compression of 3D meshes and I am trying to understand that throught your  project because it combines discret wavelets transform, quatization and zerotree coding. I have learned is far from enough for mesh compression. So, I found some ambiguities and i am asking you to help me to understand, please! 
1. could you tell me where is the progressive character in your work? 
2. can I fixe the compression ratio before applying the compression on a 3D object? (I mean fixe the number of faces or vertex that I want to obtain after compression)
3. I tried to execute the project, when I fixe the option -d 2, then I press e key,  the mesh displayed is it the one compressed? or it is the mesh just after applying the wavelet transform?
4. what is the Bounding box?
5. out.ddd is it a binary file?
6. where are levels of details are stored?
Thanks a lot

**Comment by valette** [comment]
>could you tell me where is the progressive character in your work?

Well, everything is in the papers cited in the Readme, have you read them?

> can I fixe the compression ratio before applying the compression on a 3D object? (I mean fixe the number of faces or vertex that I want to obtain after compression)

Not really, but for a given model, there are several resolution levels, maybe you could pick the one that fits better your needs?

> I tried to execute the project, when I fixe the option -d 2, then I press e key, the mesh displayed is it the one compressed? or it is the mesh just after applying the wavelet transform?

if you pressed just once, it should be the mesh after just one step of simplification

> what is the Bounding box?

Where?

> out.ddd is it a binary file?

yes

> where are levels of details are stored?

in out.ddd. This file could be split into several files (one for each resolution), I think the code could easily be changed for this.

**Comment by Salwathouir** [comment]
Well, everything is in the papers cited in the Readme, have you read them?
well i just read this one "A Wavelet-Based Progressive Compression Scheme For Triangle Meshes : Wavemesh"... normally when I said progressive compression that's mean I can stop the decompression operation at any level, depending on the terminal capacity that I have and the resoluion that I want. is not it?

if you pressed just once, it should be the mesh after just one step of simplification
when you said a step of simplification is that the same think a step of wavelet transform ? (as I know, wavelet trasform produce a coarse mesh + set of details)

what is the Bounding box?
![image](https://user-images.githubusercontent.com/38991388/44334463-7f5b2080-a469-11e8-9a5e-945f3c5e0dd5.png)
this is after after compression step

**Comment by valette** [comment]
> normally when I said progressive compression that's mean I can stop the decompression operation at any level, depending on the terminal capacity that I have and the resoluion that I want. is not it?

Yes, you can, but right now the programm reads all resolution levels, some small modification should be implemented in order to stop at a selected level

>> if you pressed just once, it should be the mesh after just one step of simplification

> when you said a step of simplification is that the same think a step of wavelet transform ? (as I know, wavelet trasform produce a coarse mesh + set of details)

Yes


> what is the Bounding box?

https://en.wikipedia.org/wiki/Minimum_bounding_box

**Comment by Salwathouir** [comment]
thank you so much for your patient explanation and for the great project you did. I hope I can achieve that level one day. have a great time Sir

**Comment by valette** [comment]
Thanks, best regards!
